name: Black

on:
  push:
    paths:
      - "**.py"
      - "**.pyi"
  pull_request:
    paths:
      - "**.py"
      - "**.pyi"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linter
        uses: psf/black@stable
        with:
          options: "--check"
          src: "."
