name: Firebase Hosting Release

on:
  push:
    branches:
      - master
    paths:
      - "web/**"
      - "docs/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: >-
          cd web && npm ci && npm run build && cd ../docs && npm ci && npm run
          build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_THIRD_CONTAINER_312001 }}"
          channelId: live
          projectId: third-container-312001
          entryPoint: web
