name: Pyright

on:
  push:
    paths:
      - "**.py"
      - "**.pyi"
  pull_request:
    paths:
      - "**.py"
      - "**.pyi"

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run pyright
        run: npm i -g pyright && pip install -r bot/requirements.txt && pyright .
