name: tests

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  pyright:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest
